# -*- coding:utf-8 -*-
class WebDataRetrievingConstants():
    massDataGrabbingDirective = "massDataGrabbingDirective"
    webPageScreenshotDirective = "webPageScreenshotDirective"
    gettingWebElementInfoDirective = "gettingWebElementInfoDirective"
    gettingWebElementPositionDirective = "gettingWebElementPositionDirective"
    gettingWebComboBoxOptionDirective = "gettingWebComboBoxOption"
    gettingWebPageInfoDirective = "gettingWebPageInfoDirective"
    gettingScrollerPositionDirective = "gettingScrollerPositionDirective"
    gettingWebDialogContentDirective = "gettingWebDialogContentDirective"
    gettingAllFilteredCookiesDirective = "gettingAllFilteredCookiesDirective"
    gettingSpecifiedCookieInfoDirective = "gettingSpecifiedCookieInfoDirective"
    startingListeningWebRequestDirective = "startingListeningWebRequestDirective"
    stoppingListeningWebRequestDirective = "stoppingListeningWebRequestDirective"
    gettingWebRequestResultDirective = "gettingWebRequestResultDirective"